version: '3.3'
services:

  jenkins-master:
    build:
      context: ./jenkins
      dockerfile: docker/master/Dockerfile
      args:
        uid: ${JENKINS_UID}
        gid: ${JENKINS_GID}
        SLAVE_HOST: ${SLAVE_HOST}
        SLAVE_HOME: ${SLAVE_HOME}
    image: jenkins-master:latest
    container_name: jenkins-master
    environment:
      JENKINS_OPTS: "--logfile=/var/log/jenkins/jenkins.log --webroot=/var/cache/jenkins/war"
      #JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    ports:
      - "8042:8080"
      - "50000:50000"
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
      - ${JENKINS_LOGS}:/var/log/jenkins
    secrets:
      - admin
      - artifactory
      - dockerhub
      - jenkinsSlaveKeys
      - gitlabKeys
      - github

  jenkins-slave:
    build:
      context: ./jenkins
      dockerfile: docker/slave/Dockerfile
      args:
        uid: $JENKINS_UID
        gid: $JENKINS_GID
    image: jenkins-slave:latest

  jenkins-slave-docker:
    build:
      context: ./jenkins
      dockerfile: docker/slave-docker/Dockerfile
    image: jenkins-slave-docker:latest
    container_name: jenkins-slave
    ports:
      - "2222:22"
    volumes:
      - ${SLAVE_HOME}:/home/jenkins
      - /var/run/docker.sock:/var/run/docker.sock

secrets:
  admin:
    file: ${SECRET_DIR}/jenkins/admin
  artifactory:
    file: ${SECRET_DIR}/jenkins/artifactory
  dockerhub:
    file: ${SECRET_DIR}/jenkins/dockerhub
  jenkinsSlaveKeys:
    file: ${SECRET_DIR}/jenkins/slave
  gitlabKeys:
    file: ${SECRET_DIR}/jenkins/gitlab
  github:
    file: ${SECRET_DIR}/jenkins/github

